### ISSUE TITLE
About the provided synthetic validataion data

### ISSUE THREAD

**Issue by Askiry** [goutamgmb/NTIRE21_BURSTSR#11]
Hi,
I wonder, whether the provided synthetic validation dataset is generated by using the script 'synthetic_burst_generation.py' with the default parameters in it? 
Because now I find that, the results on your provided val data which is submitted to the server is worse than on that generated by myself using the above provided script, and I do not know why?

**Comment by goutamgmb** [comment]
Hi,

Yes, the synthetic val set is generated using synthetic_burst_generation.py. 

The differences in results could be due to differences in the base images used to generate the bursts. Also, many parameters in the burst generation (e.g. translation amount, noise level, white balance etc) are sampled randomly. Hence bursts generated using a same image can also give different results due to the stochasticity.
