### ISSUE TITLE
The name of image files in track 2

### ISSUE THREAD

**Issue by meaten** [goutamgmb/NTIRE21_BURSTSR#14]
Hello,

I appreciate the organizers’ hard works!

The e-mail says we should follow the submission procedure for TRACK 1 to submit for TRACK2.
In TRACK 1, the name of each image file is  `burst_name` that is a return of the data loader's  `__getitem__`.
In TRACK 2, the test data loader's `__getitem__` only returns `burst` and `meta_info`.

How do we name each image file for TRACK 2 submission?
Perhaps `0638.png` or `0166_0016.png`?

Thanks!

**Comment by goutamgmb** [comment]
Hi,

Thanks for highlighting this confusion. I have now pushed a commit to the dataloader so that it also return the burst_name (e.g. `0166_0016.png`) inside the meta_info. I have also added a new script (https://github.com/goutamgmb/NTIRE21_BURSTSR/blob/master/scripts/save_results_burstsr_test.py) which you can use to save results for Track 2. It will save the results using the burst name  (e.g. `0166_0016.png`)

**Comment by meaten** [comment]
Thanks!
