### ISSUE TITLE
Deadline extension for Track 1

### ISSUE THREAD

**Issue by Magauiya** [goutamgmb/NTIRE21_BURSTSR#18]
Dear Organizers,

1. Why was the notification for deadline extension sent the day after the deadline? 
2. Can you explain what was the reason for deadline extension? 
3. Why did you extend the deadline for track 1 only? Do you have plans to extend the deadline for track 2?

Thank you!

**Comment by goutamgmb** [comment]
Hi,

1-2. Since we received relatively smaller number of submissions, we could delay processing of the results without delaying our internal timeline for the challenge paper. Hence we extended the deadline to allow for more submissions, if any.

3. The deadline extension is for both track 1 and track 2. Apologies for not stating it clearly in the email.

Regards
Goutam
