### ISSUE TITLE
The baseline solution you provided in paper 'Deep Burst Super Resolution'

### ISSUE THREAD

**Issue by Askiry** [goutamgmb/NTIRE21_BURSTSR#5]
Hi Goutam,
Thanks for your share for the baseline solution of the paper 'Deep Burst Super Resolution'.
I wonder whether and when you will release the training codes?

**Comment by martin-danelljan** [comment]
Hi Askiry.
Unfortunately we cannot release the train or test code for that paper right now until we get "OK" from the project partner due to IP rights. We hope to be able to release the code as soon as possible though. But due to this uncertainty, do not expect it to be released before the end of the challenge.

Regards,
Martin
